version: '3'
services:

  user-leave-tracking-app:
    container_name: user-leave-tracking-app
    image: user-leave-tracking-app:1
    restart: always
    build: ./
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://user-leave-tracking-mysql:3306/user_leave_tracking?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      REDIS_HOST: user-leave-tracking-redis
      REDIS_PORT: 6379
    depends_on:
      - user-leave-tracking-mysql
      - user-leave-tracking-redis

  user-leave-tracking-mysql:
    container_name: user-leave-tracking-mysql
    image: mysql:5.7
    restart: always
    platform: linux/x86_64
    environment:
       MYSQL_URL: jdbc:mysql://user-leave-tracking-mysql:3306/user_leave_tracking?autoReconnect=true&useSSL=false
       MYSQL_PASSWORD: root
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: user_leave_tracking
    volumes:
      - ./mysql:/var/lib/user-leave-tracking-mysql
    ports:
      - "3306:3306"
    expose:
      - 3306

  user-leave-tracking-redis:
    container_name: user-leave-tracking-redis
    image: redis:6.2-alpine
    restart: always
    volumes:
      - ./mysql:/var/lib/user-leave-tracking-redis
    ports:
      - '6379:6379'
    expose:
      - 6379

# docker build -t user_leave_tracking_app -f Dockerfile .
# docker ps
# docker images -a
# docker network ls
# docker run --name user_leave_tracking_app -p 8080:8080 user_leave_tracking_app
# docker image rm user_leave_tracking_app
# docker rmi $(docker images -a -q)

# docker-compose up -d