version: '3'
services:

  user-leave-tracking-app:
    container_name: user-leave-tracking-app
    image: user-leave-tracking-app:1
    build: ./
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://user-leave-tracking-mysql:3306/user_leave_tracking?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    depends_on:
      - user-leave-tracking-mysql
      - user-leave-tracking-redis

  user-leave-tracking-mysql:
    container_name: user-leave-tracking-mysql
    restart: always
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      - MYSQL_DATABASE=user_leave_tracking
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"

  user-leave-tracking-redis:
    container_name: user-leave-tracking-redis
    restart: always
    image: redis:6.2-alpine
    ports:
      - '6379:6379'

# docker-compose up -d