server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_leave_tracking
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: create
  jackson:
    serialization:
      indent-output: true
  messages:
    always-use-message-format: false
    basename: message
    encoding: UTF-8

springdoc:
  packagesToScan: com.controller
  swagger-ui:
    enabled: true
    path: /swagger-ui

redis-config:
  host: localhost
  port: 6379

user-detail:
  cacheMinute: 60