server:
  port: 8080

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/user_leave_tracking?autoReconnect=true&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
  jackson:
    serialization:
      indent-output: true
  liquibase:
    change-log=classpath:liquibase/changelog-master.xml:

redis-config:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}

springdoc:
  packagesToScan: com.controller
  swagger-ui:
    enabled: true
    path: /swagger-ui

user-detail:
  userCacheMinute: 60
  listAnnualCacheMinute: 30
  totalAnnualCacheMinute: 100